server:
  port: 8080

spring:
  application:
    name: t-bot

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}/postgres
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml
    default-schema: public

  jpa.hibernate.ddl-auto: update

bot-credentials:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  owner: ${CHAT_ID_OWNER}


